image: node:12-alpine

before_script:
  - apk update && apk upgrade && apk add --no-cache bash git openssh
  - eval $(ssh-agent -s)
  - ssh gitlab.beautybox.ru

build:
  tags: [build]
  script:
    - cp .env.example .env
    - yarn
    - yarn build
