image: node:12-alpine

before_script:
  - apk update && apk upgrade && apk add --no-cache bash git openssh
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan gitlab.beautybox.ru>> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  - ssh gitlab.beautybox.ru

build:
  tags: [build]
  script:
    - cp .env.example .env
    # - yarn
    # - yarn build
